### PR TITLE
Add time difference slide

### LINKED ISSUE #38: Show comparison of time-to-brute-force of 4 digit v. 6 digit password
For example, "wow! Using six digits, the computer took 3x as long!"

### PR DESCRIPTION
**Pull request by jamieliu386**
Fixes #38 

This PR adds a time difference screen after the second password generator for lessons 1 and 2. I also implemented the ability to go back **within** a lesson, so the users can try submitting different values without having to start the lesson over.

image
image

### CODE REVIEW

**Comment by malsf21** [comment]
The numbers are accurate, right? I think the bigger picture is the average time-to-crack, since the password-cracker isn't pseudorandom (it increments) so each password has wildly different times depending on the most significant digits.

**Comment by jamieliu386** [comment]
Yeah, the numbers are accurate based on projected time to crack the password. There's such a big fluctuation because we allow up to 12 digits, and based on the incremental password generation at 100,000 per second, the max password (999999999999) would take like 116 days.

Do you think the time should instead be an average? i.e. for a 4 digit password, the average is ~.005s and for a 6 digit password, the average is ~5s? The main thing I don't like about that is it doesn't really tie into what passwords they submitted or compare their two times directly, but I can see how using the projected time is confusing.

**Comment by krashanoff** [comment]
I think using an average as described could make sense, but only in the event that they don't allow their passwords to be cracked to completion. Thoughts?

**Comment by jamieliu386** [comment]
I'm a little hesitant to try and track whether they let the password generator finish because I feel like that's going to be messy to implement. I'm also unsure if having some times be average while others are measured might be confusing. For example, if I was going through the lesson I might wonder why the first value is a measured time but the second is an average?

I think we should either go with
1. always using the actual values for both times, or
2. always using the average values for both times.

An idea I was thinking about was lowering the upper limit on password length to something more reasonable like 8 digits, in which case the time to generate the "longest" password is ~17 minutes. This solves the issue of some of the times seeming ridiculous (like 50 days) compared to others.

I also thought about changing the phrasing on the slide from:
```
your first password was
1321
and took
4s
```
to something like:
```
your first password was
1885
and would take
0.0491s
for our password generator to guess
```
so it's not implied that we let the password generator run to completion.

What do you think?

**Comment by jamieliu386** [comment]
Also, what if we were to add a "skip" button to the password generation, allowing them to skip to the end of the animation (password and final time)? Would that be helpful or would it be more confusing?

**Comment by krashanoff** [comment]
I think both those ideas sound excellent - especially for those who are impatient.

**Comment by jamieliu386** [comment]
Ugh, unfortunately there doesn't seem to be a good way to implement the skip functionality. I'll keep trying to see if there's a hack-y way to do it, but for now I'll focus on addressing the other stuff.

**Comment by krashanoff** [comment]
Roger that. Skip functionality could be a stretch goal - besides, we'd like for kids to progress through the whole lesson piece by piece ideally, wouldn't we? Sounds AOK either way :+1:

**Comment by jamieliu386** [comment]
Yeah, I'll add an issue to the backlog for it!

**Pull request merged**
